# Generated by Django 2.0.4 on 2019-04-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=1024, null=True)),
                ('players', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('gaming_group', models.CharField(blank=True, max_length=1024, null=True)),
                ('gamemaster', models.CharField(blank=True, max_length=1024, null=True)),
                ('game_manufacture', models.CharField(blank=True, max_length=1024, null=True)),
                ('game_system', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
