# Generated by Django 2.0.4 on 2019-04-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
